services:
  db:
    image: postgres:16
    container_name: clima_pg_dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: clima_dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d clima_dev"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data_dev:
